---
# ROLE rpki_monitoring
#
# 

- name: Comienzo instalar RPKI Monitoring
  shell: | 
     echo INSTALAR RPKI MONITORING
     logger BEGIN: instalar rpki monitoring
  args:
    executable: /bin/sh

- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Install Telegraf
  apt: name=telegraf state=present

- name: Crear directorios para rpki monitoring
  file:
    path: '{{ item.dst }}'
    owner: sadmin
    group: sadmin
    state: directory
    mode: 0755
  loop:
    - { dst: /opt/rpkimon }
    - { dst: /opt/rpkimon/tals }
    - { dst: /opt/rpkimon/tals/lacnic }
    - { dst: /opt/rpkimon/fort }
    - { dst: /opt/rpkimon/octorpki }
    - { dst: /opt/rpkimon/rpki-client }
    - { dst: /opt/rpkimon/routinator }

- name: Copia scripts de lanzamiento y de colección de datos de los diferentes validadores
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    owner: '{{ item.o }}'
    group: '{{ item.g }}'
    mode: '{{ item.mode }}'
  loop:
    - { src: files/telegraf.sudo, dst: /etc/sudoers.d/telegraf, mode: '0660', o: 'root', g: 'root' }
    - { src: files/telegraf.rpki_stats.conf, dst: /etc/telegraf/telegraf.d/rpki_stats.conf, mode: '0644', o: 'sadmin', g: 'sadmin' }
    - { src: files/lacnic.tal, dst: /opt/rpkimon/tals, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/lacnic.tal, dst: /opt/rpkimon/tals/lacnic, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort.launch.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort.collect.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.launch.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.collect.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    # - { src: files/named.slaves.conf, dst: /home/bind9/etc/ }
    # - { src: files/named.masters.conf, dst: /home/bind9/etc/ }
    # - { src: files/named.logging.conf, dst: /home/bind9/etc/ }
    # - { src: files/db.pande.mia, dst: /home/bind9/var/zones }

- name: Reinicio el telegraf
  service:
     name: telegraf
     state: restarted



# - name: Instalar dependencias para el server
#   apt: 
#     pkg: 
#       - sudo
#       - vim-tiny
#       - figlet
#       - make
#       - rsync
#       - bind9-utils
#       - net-tools
#       - htop
#       - fail2ban
#     update_cache: yes

# # Los usuarios a crear se definen en la variable usuarios
# - name: Crear usuarios (carlos, sadmin, etc.)
#   user: 
#     name: "{{ item }}"
#     state: present
#     shell: /bin/bash
#     home: "/home/{{ item }}"
#     append: yes
#     groups: sudo
#   loop: '{{ usuarios }}'

# # Una clave por usuario, hay que llamarlas id.pub.<<usuario>>'
# - name: Copia las claves publicas al servidor remoto
#   copy:
#     src: "id.pub.{{ item }}"
#     dest: /var/run
#   loop: '{{ usuarios }}'
  
# - name: Configurar las claves publicas de los usuarios
#   authorized_key:
#     user: "{{ item }}"
#     state: present
#     # key: "{{ lookup('file', '/var/run/id.pub.'+item) }}"
#     key: "{{ lookup('file', 'id.pub.'+item) }}"
#   loop: '{{ usuarios }}'

# - name: Deshabilito UFW
#   ufw:
#     state: disabled

# - name: Levanto el fail2ban corriendo
#   service:
#      name: fail2ban
#      state: started
