---
# ROLE rpki_monitoring
#
# 

- name: Comienzo instalar RPKI Monitoring
  shell: | 
     echo INSTALAR RPKI MONITORING
     logger BEGIN: instalar rpki monitoring
  args:
    executable: /bin/sh

- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Instalar paquetes auxiliares (tree, jq)
  apt: 
    pkg: 
      - tree
      - jq
      - figlet
      - nginx
    update_cache: no

- name: Install Telegraf
  apt: name=telegraf state=present

- name: Install InfluxDB packages
  apt: name=influxdb state=present

- name: Hacer que influx escuche solo en localhost
  shell: |
    sed  -i.bak 's/\# bind-address = ":8086"/ bind-address = "127.0.0.1:8086"/' /etc/influxdb/influxdb.conf
  args:
    executable: /bin/sh

- name: Install Grafana y asegurar que solo escuche en localhost
  shell: |
    cd /tmp
     sudo apt-get install -y adduser libfontconfig1
     wget https://dl.grafana.com/enterprise/release/grafana-enterprise_8.1.5_amd64.deb
     sudo dpkg -i grafana-enterprise_8.1.5_amd64.deb
     sed -i.bak 's/\;http_addr\ \=/http_addr=127.0.0.1/' /etc/grafana/grafana.ini
  args:
    executable: /bin/sh

- name: Modify InfluxDB hostname
  replace:
    dest=/etc/influxdb/influxdb.conf
    regexp='hostname = "localhost"'
    replace='hostname = "{{ ansible_hostname }}"'
    backup=yes

- name: Crear directorios para rpki monitoring
  file:
    path: '{{ item.dst }}'
    owner: '{{ item.o }}'
    group: '{{ item.g }}'
    state: directory
    mode: '{{ item.mode }}'
  loop:
    - { dst: /opt/rpkimon, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/tals, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/tals/lacnic, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/tals/apnic, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/tals/afrinic, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/octorpki, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/rpki-client, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { dst: /var/lib/grafana/dashboards, mode: '0755', o: 'root', g: 'root' }

- name: Copia scripts de lanzamiento y de colección de datos de los diferentes validadores
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    owner: '{{ item.o }}'
    group: '{{ item.g }}'
    mode: '{{ item.mode }}'
  loop:
    - { src: files/telegraf.sudo, dst: /etc/sudoers.d/telegraf, mode: '0660', o: 'root', g: 'root' }
    - { src: files/dashboardFileProvisioner.yml, dst: /etc/grafana/provisioning/dashboards, mode: '0644', o: 'root', g: 'root' }
    - { src: files/influxdbv1Provisioner.yml, dst: /etc/grafana/provisioning/datasources, mode: '0644', o: 'root', g: 'root' }
    - { src: files/rpki-stats-v1.json, dst: /var/lib/grafana/dashboards, mode: '0644', o: 'root', g: 'root' }
    - { src: files/telegraf.rpki_stats.conf, dst: /etc/telegraf/telegraf.d/rpki_stats.conf, mode: '0644', o: 'sadmin', g: 'sadmin' }
    - { src: files/lacnic.tal, dst: /opt/rpkimon/tals, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/lacnic.tal, dst: /opt/rpkimon/tals/lacnic, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/apnic.tal, dst: /opt/rpkimon/tals/apnic, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/afrinic.tal, dst: /opt/rpkimon/tals/afrinic, mode: '0664', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort.launch.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort.collect.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort-rsync.launch.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/fort-rsync.collect.sh, dst: /opt/rpkimon/fort, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.launch.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.collect.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.launch.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/routinator.collect.sh, dst: /opt/rpkimon/routinator, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/rpki-client.launch.sh, dst: /opt/rpkimon/rpki-client, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/rpki-client.collect.sh, dst: /opt/rpkimon/rpki-client, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/octorpki.launch.sh, dst: /opt/rpkimon/octorpki, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/octorpki.collect.sh, dst: /opt/rpkimon/octorpki, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/nginx.site.default, dst: /etc/nginx/sites-available/default, mode: '0644', o: 'root', g: 'root' }
    - { src: files/preval_stats.collect.sh, dst: /opt/rpkimon/preval_stats.collect.sh, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/influx_cleanup.sh, dst: /opt/rpkimon/influx_cleanup.sh, mode: '0755', o: 'sadmin', g: 'sadmin' }
    - { src: files/nginx-selfsigned.crt, dst: /etc/ssl/certs/nginx-selfsigned.crt, mode: '0644', o: 'root', g: 'root' }
    - { src: files/nginx-selfsigned.key, dst: /etc/ssl/private/nginx-selfsigned.key, mode: '0600', o: 'root', g: 'root' }


- name: Self-signed cert generation for NGINX
  shell: |
     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509  \
       -subj "/C=UY/ST=MVD/L=Montevideo/O=Dis/CN=localhost"  \
       -keyout /etc/ssl/private/nginx-selfsigned.key  \
       -out /etc/ssl/certs/nginx-selfsigned.crt
       #
       touch /var/local/self_signed_cert_created
  args:
    executable: /bin/sh
    creates: /var/local/self_signed_cert_created

- name: Reinicio el telegraf
  service:
     name: telegraf
     state: restarted
     enabled: yes

- name: Reinicio el InfluxDB
  service:
     name: influxdb
     state: restarted
     enabled: yes

- name: Reinicio el Grafana
  service:
     name: grafana-server
     state: restarted
     enabled: yes

- name: Reinicio el NGINX
  service:
     name: nginx
     state: restarted
     enabled: yes

- name: Lanzo los containers de los validadores
  shell: | 
     cd /opt/rpkimon
     logger Lanzando los containers
     ./fort/fort.launch.sh
     ./fort/fort-rsync.launch.sh
     ./routinator/routinator.launch.sh
     ./rpki-client/rpki-client.launch.sh
     ./octorpki/octorpki.launch.sh
     touch /var/local/containers_launched
  args:
    executable: /bin/sh
    creates: /var/local/containers_launched


